"""initial

Revision ID: 755825d4c6b7
Revises: 
Create Date: 2026-06-20 17:09:19.585538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '755825d4c6b7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_employees_country'), 'employees', ['country'], unique=False)
    op.create_index(op.f('ix_employees_department'), 'employees', ['department'], unique=False)
    op.create_index('ix_employees_department_country', 'employees', ['department', 'country'], unique=False)
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=True)
    op.create_index(op.f('ix_employees_is_active'), 'employees', ['is_active'], unique=False)
    op.create_index('ix_employees_name', 'employees', ['last_name', 'first_name'], unique=False)
    op.create_table('payroll_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pay_period_start', sa.Date(), nullable=False),
    sa.Column('pay_period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PROCESSING', 'PAID', 'FAILED', name='batchstatus'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pay_period_start', 'pay_period_end', name='uq_batch_period')
    )
    op.create_index('ix_batches_status', 'payroll_batches', ['status'], unique=False)
    op.create_table('payroll_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('base_salary_snapshot', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('allowances_snapshot', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deductions_snapshot', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_salary_snapshot', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='recordstatus'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['payroll_batches.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_records_batch_status', 'payroll_records', ['batch_id', 'status'], unique=False)
    op.create_index('ix_records_employee', 'payroll_records', ['employee_id'], unique=False)
    op.create_table('salary_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('allowances', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contracts_employee_active', 'salary_contracts', ['employee_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_salary_contracts_employee_id'), 'salary_contracts', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salary_contracts_employee_id'), table_name='salary_contracts')
    op.drop_index('ix_contracts_employee_active', table_name='salary_contracts')
    op.drop_table('salary_contracts')
    op.drop_index('ix_records_employee', table_name='payroll_records')
    op.drop_index('ix_records_batch_status', table_name='payroll_records')
    op.drop_table('payroll_records')
    op.drop_index('ix_batches_status', table_name='payroll_batches')
    op.drop_table('payroll_batches')
    op.drop_index('ix_employees_name', table_name='employees')
    op.drop_index(op.f('ix_employees_is_active'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.drop_index('ix_employees_department_country', table_name='employees')
    op.drop_index(op.f('ix_employees_department'), table_name='employees')
    op.drop_index(op.f('ix_employees_country'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
